name: Android CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew test

      - name: Send Mail 发送邮件
        uses: bingblue/send-nodemailer@master
        with:
          # 账号
          user: '${{ secrets.MAIL_USER }}'
          # 密码
          pass: '${{ secrets.MAIL_PASS }}'
          # Host，在邮箱的设置里可以找到
          host: 'smtp.qq.com'
          # 端口
          port: 465
          # 是否开启SSL
          secure: true
          # 发送者
          from: 'Your Name <youremail@gmail.com>'
          # 收件人
          to: 380286681@qq.com
          # 主题
          subject: 'this is email subject'
          # Use html file prefix [file://]，使用HTML文件，已[file://]开头
          html: '<p>this is content</p>'
          # Or use html script，或者使用HTML代码片段
          # html: '<p>this is content</p>'
